### ISSUE TITLE
Merge kameleon-bootstrap-recipes ?

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon-recipes#13]
@SalemHarrache : we are trying to build a debian9, but no bootstrap exists yet of that version.

We could build and host one, but yet we do not understand why we have to rely on such a bootstrap.. Is it a part of what is actually shipped in the builded env ? If yes, that would mean we do not control every steps of the build in our recipes ? We would prefere having a raw debootstrap here..

Could you explain ?

**Comment by SalemHarrache** [comment]
The short answer is : stability.

We encountered some issues to have recipes stable both in time and in the various environments (virtual machine, user OS, tools version).They were mainly due to the bootstrap step. It is the most
instable step because, except Debian and possibly archlinux, no distribution can bootstrap appropriately in a trivial way.

So I switch between installing debootstrap, kickstart, pressed.cfg, iso, netinstall...

For all these reasons, we decided to split the initial repository into two different repots:

- **kameleon-bootstrap-recipes**: recipes which create a very basic rootfs and which will support a restricted number of execution environments (stable qemu+debian)

- **kameleon-recipes**: a more stable repository to most non-expert users that want to custom a little bit their image. There is little change compared to the previous one, it's just that instead of using debootstrap, we will use a simple ``wget $$rootfs_url`` to get the archive produced by the bootstrap recipes.

That's the best solution I've found to have some stability in Kameleon recipes, since maintenance was demanding and I didn't have a lot of time to devote to it.

**Comment by npf** [comment]
So I do you see it from a user's perspective ?

One would like to control every steps from the beginning.
-> should the user clone the kameleon-bootstrap-recipes, and do some changes here eventually ? How could it benefit from change here in its recipes ? (it kameleon-bootstrap-recipes thought to be placed in the hands of the end users ?)
-> would it be possible to let the use choose whether he wants to use debootstrap or a rootfs generated from kameleon-bootstrap-recipes ?

**Comment by npf** [comment]
Please not that the actual/current use case is a user that wants Debian testing (Debian 9, stretch).
No rootfs is provided for now. What would you propose for him ?

**Comment by mickours** [comment]
The user is @Shurakai by the way :)

**Comment by SalemHarrache** [comment]
Hi,

I think we can merge both repositories so that the task is both accessible to beginners and advanced users.

However, bootstrap recipes will only be supported by qemu, as it is the only one
which covers all bootstrap methods that we developped (kickstart, debootstrap, iso, etc.)

For now, the kameleon-recipes repository looks like this:

```
.
├── chroot/
├── docker/
├── grid5000/
├── qemu/
├── vagrant/
└── virtualbox/
```

If I merge both repositories, we will have something like that:

```
.
├── qemu-bootstrap/
├── chroot/
├── docker/
├── grid5000/
├── qemu/
├── vagrant/
└── virtualbox/
```

For example, if I want to add a new recipe ``debian9``, I will first add the bootstrap recipe in the ``qemu-bootstrap`` directory, then a standard recipe in the chroot|docker|virtualbox|qemu|xxx directories.

Thanks to the inheritance, this task is relatively trivial.

What do you guys think about it?

**Comment by npf** [comment]
What about having (qemu only) bootstraps in the qemu directory ?
Could bootstrap recipes be prefixed bootstrap-* for instance, ditto for steps ?

**Comment by SalemHarrache** [comment]
why not, It sounds good :)

**Comment by npf** [comment]
:+1:

**Comment by mickours** [comment]
Ok for me :)

**Comment by npf** [comment]
Then, I propose:
  * to rename recipes for bootstrap as qemu/<distro-name>-bootstrap.yaml (add the -bootstrap suffix)
  * merge the steps, which hopefully will not conflict :-)
I'll give a try to that soon unless anyone is quicker.

**Comment by mickours** [comment]
Done in the refactor branch (to test)

**Comment by mickours** [comment]
From scratch recipes tested:
- [x] archlinux.yaml
- [ ] centos6.yaml (not working)
- [x] centos7.yaml
- [ ] debian7-netinstall.yaml
- [ ] debian8-arm64.yaml
- [ ] debian8-netinstall.yaml
- [ ] debian8.yaml
- [ ] debian-base-netinstall.yaml
- [ ] debian-base.yaml
- [ ] debian-sid-arm64.yaml
- [ ] debian-sid.yaml
- [ ] debian-testing-arm64.yaml
- [ ] debian-testing.yaml
- [ ] fedora20.yaml
- [ ] fedora21.yaml
- [ ] fedora22.yaml
- [ ] fedora23.yaml
- [ ] fedora-base.yaml
- [ ] nixos.yaml
- [ ] ubuntu12.04.yaml
- [ ] ubuntu14.04.yaml
- [ ] ubuntu-base.yaml

**Comment by npf** [comment]
Merge of the 2 repositories and refactoring is now pushed in the master branch.
